imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    FOSUserBundle: ~
                    SonataUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Gcmaz\UserBundle\Entity\User
    group:
        group_class: Gcmaz\UserBundle\Entity\Group
    profile: # Authentication Form
        form:
            type: fos_user_profile
            handler: fos_user.profile.form.handler.default
            name: fos_user_profile_form
            validation_groups: [Authentication] # Please note : this is not default value

sonata_user:
    security_acl: true
    class:
        user: Gcmaz\UserBundle\Entity\User
        group: Gcmaz\UserBundle\Entity\Group
    admin:   # Admin Classes
        user:
            class: Sonata\UserBundle\Admin\Entity\UserAdmin
            controller: SonataAdminBundle:CRUD
            translation: SonataUserBundle
 
        group:
            class: Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller: SonataAdminBundle:CRUD
            translation: SonataUserBundle
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type: sonata_user_profile
            handler: sonata.user.profile.form.handler.default
            name: sonata_user_profile_form
            validation_groups:  [Profile]

sonata_admin:
    title:      GCM Admin
    templates:
        ## default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
 
        ## default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        history: SonataAdminBundle:CRUD:history.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        delete:  SonataAdminBundle:CRUD:delete.html.twig
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

sonata_intl:
    timezone:
        default: America/Phoenix

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
 
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
            
sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        #the default context is mandatory
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.youtube
                #- sonata.media.provider.dailymotion
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        
        #concert listings
        concerts:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 150 , quality: 70}
                
        #whats happening listings
        whats:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 600 , quality: 70}
                
        #community listings
        community:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 600 , quality: 70}
                
        #reator listings - dream home        
        realtor:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.youtube
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 600 , quality: 70}
                
        #pet listings - dream home        
        pet:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.youtube
            formats:
                small: { width: 150 , quality: 70}
                big:   { width: 250 , quality: 70}
 
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/
 
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
            
    providers:
        image:
            resizer: sonata.media.resizer.square
            
ivory_ck_editor:
    enable: true
    base_path: "/bundles/ivoryckeditor/"
    js_path: "/bundles/ivoryckeditor/ckeditor.js"
    configs:
        cms_pet:
            toolbar:  "cms_tb_sm"
            ui_color: "#ffffff"
            height: "250"
            width: "600"
            forcePasteAsPlainText: true
        cms_concert:
            toolbar:  "cms_tb_sm"
            ui_color: "#ffffff"
            height: "250"
            width: "600"
            forcePasteAsPlainText: true
    toolbars:
        configs:
            cms_tb_lg: [ "@document", "@styles", "@color", "/", "@basicstyles", "@paragraph", "@link", "/", "@source", "@tool1", "@tool2" ]
            cms_tb_med: ["@document", "@styles", "@color", "/", "@basicstyles", "@paragraph", "@link", "/", "@source", "@tool1", "@tool2"]
            cms_tb_sm: ["@basicstyles", "@color", "@link"]
        items:
            document: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "Undo", "Redo"  ]
            styles: [ "Styles", "Format", "Font", "FontSize" ]
            color: [ "TextColor", "BGColor" ]
            basicstyles: [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat" ]
            paragraph: [ "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote", "CreateDiv", "-", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "-", "BidiLtr", "BidiRtl" ]
            link:     [ "Link", "Unlink" ]
            source: [ "Source" ]
            tool1:     [ "Maximize" ]
            tool2:     [ "Save" ]

fos_facebook:
    alias:  facebook
    app_id: 699635690051270
    secret: b1240160cb3f44e42f2fe5228020a7fe
    cookie: true
    permissions: [email, user_location]