<?php

namespace Gcmaz\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhotocontestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotocontestRepository extends EntityRepository
{
    public function getPhotocontest()
    //$gid is above param passed in if narrowing
    {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                //->where('g.id = :gid')
                //$qb->setMaxResults(1)
                ;
                
        return $qb->getQuery()
                       ->getResult();
    }
}
