<?php

namespace Gcmaz\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotocontestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotocontestRepository extends EntityRepository
{
    public function getPhotocontest()
    //$gid is above param passed in if narrowing
    {
        $qb = $this->createQueryBuilder('x')
                ->select('x')
                ;
                
        
        return $qb->getQuery()
                       ->getResult();
    }
}
