<?php

namespace Gcmaz\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotocontestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotocontestRepository extends EntityRepository
{
}
