<?php

namespace Gcmaz\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RealtorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealtorRepository extends EntityRepository
{
}
