gcm_homepage:
    pattern:  /
    defaults: { _controller: GcmazMainBundle:Page:index }

gcm_contact:
    path: /contact/great-circle-media
    defaults: { _controller: GcmazMainBundle:Page:contact }
