parameters:
#    gcmaz_main.example.class: Gcmaz\MainBundle\Example

services:
#    gcmaz_main.example:
#        class: %gcmaz_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
